### ISSUE TITLE
ModlistCreator fails frequently with `--detailed` flag

### ISSUE THREAD

**Issue by NielsPilgaard** [ModdingX/ModListCreator#17]
It looks like the good old CurseForgeAPI acting up, but is there anything you guys can do to make it fail less frequently perhaps? 😅 
Without the `--detailed` flag it's pretty much instant.

Used command: `java -jar "ModListCreator-4.0.1-fatjar.jar" modlist --output "changelogs/modlist_1.5.0.md" --detailed "Enigmatica6-1.5.0.zip"`
Output from the console: https://gist.github.com/NielsPilgaard/22995e96c2dee72ea9231f3a6c6dad98

**Comment by MelanX** [comment]
The problem with the detailed flag is that it will requests the data for every single file one by one. Without it, the whole data will be requested in one step - because it's possible. By requesting one by one, there are maybe 300 more requests than without the detailed flag. And if there are more requests, the chance is much higher that it could happen. I don't know if we can do anything about it but I don't think so. As you said, the good old CurseForge API is messing up :/
Maybe @noeppi-noeppi can be more clearly if there's a way to make it less frequently failing.

**Comment by NielsPilgaard** [comment]
Perhaps you could:
- (try-)catch the exception
- cache progress (or rather, don't discard it)
- wait and retry with exponential backoff

It would be important to provide log output though, so the user knows somethings actually going on, as it could take hours (I'm guessing) 😄 .

**Comment by MelanX** [comment]
True, I only thought about server side things and not re-trying within the tool itself. That would be actually smart. 
And yes, I should re-add the log if you use `--detailed`. That was deleted during implementation of Modrinth support.

**Comment by NielsPilgaard** [comment]
Thank you kindly :D that ought to help

**Comment by NielsPilgaard** [comment]
I find that this has helped a ton, using the `--detailed` flag is much more reliable now, thanks 👍
